permalink: /:categories/:title.html
url: "https://dx2ta2.github.io/"
full_name: "DX2"
first_name: "5kin studio"
last_name: "-Artsit DX2"
blog_title: "Dx2"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: ""
facebook: "mepasindu"
linkined_url: ""